# Configuration file for config/secrets.yml
# FluxPay Platform

development:
  # TODO: Add development configuration
  
test:
  # TODO: Add test configuration
  
production:
  # TODO: Add production configuration
